openapi: 3.0.0
info:
  title: API de Productos
  description: API para gestionar productos
  version: 1.0.0
  contact: 
    name: bruno fresilli  
    email: brunofresilli11@gmail.com

servers:
  - url: http://localhost:8080
    description: Servidor local

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: string
        thumbnails:
          type: array
          items:
            type: string
        owner:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string

paths:
  /products:
    get:
      summary: Obtener productos
      security:
        - jwt: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Error al obtener productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Crear un nuevo producto
      security:
        - jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error al crear el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products/{pid}:
    get:
      summary: Obtener un producto por ID
      security:
        - jwt: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        '200':
          description: Producto obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error al obtener el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Actualizar un producto
      security:
        - jwt: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error al actualizar el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Eliminar un producto
      security:
        - jwt: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        '200':
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Error al eliminar el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
